title    = "[bold italic #fea62b on #24292f underline]"
subtitle = "[bold red3 underline]"
success  = "[bold #7ae998 underline]"
error    = "[bold #b93c5b]"
warning  = "[bold #ffe46b]"
item     = "[bold italic #36aa5e]"
fnum     = "[green]"